// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMAnager.Nexus.Data;

#nullable disable

namespace UMAnager.Nexus.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515192837_Phase5A_BreedingHorses")]
    partial class Phase5A_BreedingHorses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMAnager.Nexus.Data.Entities.AppState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("app_state", (string)null);
                });

            modelBuilder.Entity("UMAnager.Nexus.Data.Entities.Horse", b =>
                {
                    b.Property<string>("HorseId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("BmsId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DamId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NameEn")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NameJa")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PedigreeJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("SireId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("HorseId");

                    b.HasIndex("HorseId")
                        .IsUnique();

                    b.ToTable("horses", (string)null);
                });

            modelBuilder.Entity("UMAnager.Nexus.Data.Entities.Race", b =>
                {
                    b.Property<string>("RaceId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<short>("DataStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<int?>("Distance")
                        .HasColumnType("integer");

                    b.Property<bool>("HistoryRefreshed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("LastModified")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NameJa")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RaceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ResultsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("SortTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Surface")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TrackCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("RaceId");

                    b.HasIndex("RaceDate");

                    b.HasIndex("RaceId")
                        .IsUnique();

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("UMAnager.Nexus.Data.Entities.RaceEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int?>("Bracket")
                        .HasColumnType("integer");

                    b.Property<short>("DataStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<int?>("FavRank")
                        .HasColumnType("integer");

                    b.Property<int?>("FinishPos")
                        .HasColumnType("integer");

                    b.Property<string>("HorseId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("HorseWeight")
                        .HasColumnType("integer");

                    b.Property<string>("JockeyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly?>("LastModified")
                        .HasColumnType("date");

                    b.Property<decimal?>("Odds")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("PerformanceJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("PostPosition")
                        .HasColumnType("integer");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HorseId");

                    b.HasIndex("RaceId");

                    b.HasIndex("RaceId", "HorseId")
                        .IsUnique();

                    b.ToTable("race_entries", (string)null);
                });

            modelBuilder.Entity("UMAnager.Nexus.Data.Entities.RawStagingRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RawBytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("RecordType", "IsProcessed");

                    b.ToTable("raw_staging", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
